#!/bin/bash
[ -r ~/.config/bnotifyd.conf ] && . ~/.config/bnotifyd.conf || exit 1

trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT

for i in "${!class[@]}"; do
	max[$i]=$(cat "/sys/class/${class[$i]}/max_brightness")
	prev[$i]=$(cat "/sys/class/${class[$i]}/brightness")
done

check () {
	cur=$(cat "/sys/class/${class[$i]}/brightness")
	if [ "$cur" == "${prev[$1]}" ]; then
		return 1
	fi
	prev[$i]=$cur
	perc=$(printf "%.0f\n" $(bc<<<"scale=2; $cur/${max[$1]}*100"))
	notify-send.sh -R /tmp/${type[$i]}.notify -t 50 -h int:value:$perc -i ${type[$i]}-brightness-symbolic Brightness
}

# Detect if brightness value is updated by acpid itself
for i in "${!class[@]}"; do (
	while inotifywait -qq -e close_write "/sys/class/${class[$i]}/brightness"; do
		check $i
	done
	) &
done

# Check on acpi events if brightness change cannot be detected by inotify
acpi_listen | while IFS= read -r l; do
	for i in "${!class[@]}"; do
		check $i && break
	done
done
